version: "3.8"
services:
  postgres:
    image: postgres:alpine
    user: postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      # Any SQL scripts in this directory are executed on first run
      # - ./db/init:/docker-entrypoint-initdb.d
      - database:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "${COMPOSE_LOG_DRIVER}"
  bot:
    build: .
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      OCTOKIT_TOKEN: ${OCTOKIT_TOKEN}
      MONGODB_URL: UNUSED
      CHALLONGE_USERNAME: ${CHALLONGE_USERNAME}
      CHALLONGE_TOKEN: ${CHALLONGE_TOKEN}
      POSTGRESQL_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}"
      EMCEE_USE_POSTGRES: 1
      DEBUG: "emcee:*"
    volumes:
      - ./dbs:/app/dbs
      - ./logs:/app/logs
      - ./ormlogs.log:/app/ormlogs.log
    restart: unless-stopped
    logging:
      driver: "${COMPOSE_LOG_DRIVER}"

volumes:
  database:
