version: "3.8"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - tournamentdb:/data/db
    restart: unless-stopped
  postgres:
    image: postgres:alpine
    user: postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      # Any SQL scripts in this directory are executed on first run
      # - ./db/init:/docker-entrypoint-initdb.d
      - database:/var/lib/postgresql/data
    restart: unless-stopped
  bot:
    build: .
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      OCTOKIT_TOKEN: ${OCTOKIT_TOKEN}
      MONGODB_URL: mongodb://mongo:27017/tournamentdb
      CHALLONGE_USERNAME: ${CHALLONGE_USERNAME}
      CHALLONGE_TOKEN: ${CHALLONGE_TOKEN}
      POSTGRESQL_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}"
    volumes:
      - ./dbs:/app/dbs
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  tournamentdb:
  database:
