# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run cover
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }},
          OCTOKIT_TOKEN: ${{ secrets.OCTOKIT_TOKEN }},
          MONGODB_URL: mongodb://localhost:27017/tournamentdb
